import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const api = readFileSync(new URL('../../lib/api.ts', import.meta.url), 'utf8');
const card = readFileSync(new URL('./WorkflowCard.tsx', import.meta.url), 'utf8');
const windowSource = readFileSync(new URL('./WorkflowWindow.tsx', import.meta.url), 'utf8');
const chatCard = readFileSync(new URL('./ChatWorkflowCard.tsx', import.meta.url), 'utf8');
const graphBoard = readFileSync(new URL('./WorkflowGraphBoard.tsx', import.meta.url), 'utf8');
assert.ok(api.includes('async function stopExecution('));
assert.ok(api.includes('stopExecution,'));
assert.ok(api.includes('/stop`'));
assert.ok(api.includes('async function markExecutionCompleted('));
assert.ok(api.includes('markExecutionCompleted,'));
assert.ok(api.includes('/complete`'));
assert.ok(card.includes('const handleStopExecution'));
assert.ok(card.includes('workflowApi.stopExecution('));
assert.ok(card.includes('onStopExecution={handleStopExecution}'));
assert.ok(card.includes("'resume-execution'"));
assert.ok(card.includes("'stop-execution'"));
assert.ok(card.includes('pendingActionType={pendingActionType}'));
assert.ok(card.includes('const handleMarkExecutionCompleted'));
assert.ok(card.includes('workflowApi.markExecutionCompleted('));
assert.ok(
  card.includes('onMarkExecutionCompleted={handleMarkExecutionCompleted}'),
);
assert.ok(windowSource.includes("useCommandHandler('workflow.start'"));
assert.ok(windowSource.includes("useCommandHandler('workflow.node.stop'"));
assert.ok(windowSource.includes("useCommandHandler('workflow.stop'"));
assert.ok(windowSource.includes('type StopConfirmation ='));
assert.ok(windowSource.includes("{ kind: 'step'; stepId: string }"));
assert.ok(windowSource.includes("{ kind: 'execution'; executionId: string }"));
assert.ok(windowSource.includes('onStopStep?.(stopConfirmation.stepId)'));
assert.ok(windowSource.includes('onStopExecution?.(stopConfirmation.executionId)'));
assert.ok(windowSource.includes("pendingActionType === 'resume-execution'"));
assert.ok(windowSource.includes("pendingActionType === 'stop-execution'"));
assert.ok(windowSource.includes('<LoaderCircle'));
assert.ok(windowSource.includes('<BadgeCheck'));
assert.ok(windowSource.includes('text-amber-500'));
assert.ok(windowSource.includes('workflow.controls.markCompleted'));
assert.ok(windowSource.includes('workflow.confirm.markCompletedTitle'));
assert.ok(windowSource.includes('canMarkWorkflowExecutionCompleted(projection)'));
assert.ok(windowSource.includes('onMarkExecutionCompleted?.(completionConfirmationExecutionId)'));
assert.ok(chatCard.includes('workflow.controls.markCompleted'));
assert.ok(chatCard.includes('workflow.confirm.markCompletedTitle'));
assert.ok(chatCard.includes('canMarkWorkflowExecutionCompleted(projection)'));
assert.ok(chatCard.includes('onMarkExecutionCompleted?.(projection.execution_id!)'));
assert.ok(chatCard.includes("pendingActionType === 'resume-execution'"));
assert.ok(chatCard.includes('<LoaderCircle'));
assert.ok(chatCard.includes('<BadgeCheck'));
assert.ok(chatCard.includes('text-amber-500'));
assert.ok(graphBoard.includes('<LoaderCircle'));
const confirmBlock = windowSource.slice(windowSource.indexOf('const confirmStop'));
assert.equal(confirmBlock.slice(0, confirmBlock.indexOf('};') + 2).includes('onPauseAll'), false);
assert.equal(chatCard.includes('{projection.stopped_by_user}'), false);
assert.ok(chatCard.includes('projection.error_message'));
console.log('Workflow stop shortcut wiring: PASS');
